# Generated by Django 3.2.25 on 2024-04-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestPortal_App', '0002_rename_question_questionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='correctOption',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option1',
            field=models.CharField(default='hi', max_length=250),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option2',
            field=models.CharField(default='hi', max_length=250),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option3',
            field=models.CharField(default='hi', max_length=250),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='option4',
            field=models.CharField(default='hi', max_length=250),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.CharField(default='hi', max_length=500),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(max_length=250)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_scheduled', models.DateTimeField()),
                ('time_ending', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestPortal_App.quiz'),
        ),
    ]
